### ISSUE TITLE
coc-html error on loading ConnectionError: Connection is disposed.

### ISSUE THREAD

**Issue by agtonybarletta** [neoclide/coc-html#30]
I am trying to use *coc-prettier* to prettify html files, when I enable *coc-html* it pops up this error.

```
[coc.nvim]: ConnectionError: Connection is disposed.
    at throwIfClosedOrDisposed (/home/tony/.vim/plugged/coc.nvim/build/index.js:17398:19)
    at Object.sendNotification (/home/tony/.vim/plugged/coc.nvim/build/index.js:17445:13)
    at /home/tony/.vim/plugged/coc.nvim/build/index.js:17572:32
    at CallbackList.invoke (/home/tony/.vim/plugged/coc.nvim/build/index.js:18265:39)
    at Emitter.fire (/home/tony/.vim/plugged/coc.nvim/build/index.js:18324:36)
    at MutableToken.cancel (/home/tony/.vim/plugged/coc.nvim/build/index.js:18582:31)
    at CancellationTokenSource.cancel (/home/tony/.vim/plugged/coc.nvim/build/index.js:18623:25)
    at Highlighter.cancel (/home/tony/.vim/plugged/coc.nvim/build/index.js:96071:30)
    at Highlighter.doHighlight (/home/tony/.vim/plugged/coc.nvim/build/index.js:95974:18)
    at Highlighter.<anonymous> (/home/tony/.vim/plugged/coc.nvim/build/index.js:95955:18)
    at Timeout.later [as _onTimeout] (/home/tony/.vim/plugged/coc.nvim/build/index.js:22043:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 2
}
```

The language server in the editor doesn't work, `:CocNext` doesn't find any error,
`:CocCommand prettier.formatFile` doesn't format anything and no messagges it is shown.

I tried to fix and reload *coc-html* and *coc-prettier*.

List of plugins
```
coc-prettier 1.1.20 ~/.config/coc/extensions/node_modules/coc-prettier                                                                                                                                                               
  * coc-lists 1.3.16 ~/.config/coc/extensions/node_modules/coc-lists
  * coc-html 1.3.1 ~/.config/coc/extensions/node_modules/coc-html
  * coc-git 2.0.5 ~/.config/coc/extensions/node_modules/coc-git
  * coc-eslint 1.3.2 ~/.config/coc/extensions/node_modules/coc-eslint
  + coc-tsserver 1.6.3 ~/.config/coc/extensions/node_modules/coc-tsserver
  + coc-markdownlint 1.9.0 ~/.config/coc/extensions/node_modules/coc-markdownlint
  + coc-json 1.3.2 ~/.config/coc/extensions/node_modules/coc-json
  + coc-clangd 0.6.0 ~/.config/coc/extensions/node_modules/coc-clangd
```

`:CocInfo`
```
## versions

vim version: NVIM v0.4.4
node version: v12.18.1
coc.nvim version: 0.0.79-f2afd214ba
coc.nvim directory: /home/tony/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-12-13T11:14:27.444 INFO (pid:17933) [services] - registered service "eslint"
2020-12-13T11:14:27.511 INFO (pid:17933) [services] - registered service "html"
2020-12-13T11:14:27.512 INFO (pid:17933) [services] - HTML language server state change: stopped => starting
2020-12-13T11:14:27.723 INFO (pid:17933) [language-client-index] - html started with 17950
2020-12-13T11:14:27.781 INFO (pid:17933) [plugin] - coc.nvim 0.0.79-f2afd214ba initialized with node: v12.18.1 after 500ms
2020-12-13T11:14:28.185 INFO (pid:17933) [services] - HTML language server state change: starting => running
2020-12-13T11:14:28.198 INFO (pid:17933) [services] - service html started
2020-12-13T11:17:36.243 INFO (pid:17933) [services] - HTML language server state change: running => stopped
2020-12-13T11:17:44.228 WARN (pid:17933) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/home/tony/.vim/plugged/coc.nvim/build/index.js:16589:25)
    at ListManager.init (/home/tony/.vim/plugged/coc.nvim/build/index.js:83816:26)
    at Plugin.init (/home/tony/.vim/plugged/coc.nvim/build/index.js:23986:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/tony/.vim/plugged/coc.nvim/build/index.js:11641:13
2020-12-13T11:17:44.496 INFO (pid:17933) [services] - registered service "html"
2020-12-13T11:17:44.496 INFO (pid:17933) [services] - HTML language server state change: stopped => starting
2020-12-13T11:17:44.503 INFO (pid:17933) [language-client-index] - html started with 18202
2020-12-13T11:17:44.912 INFO (pid:17933) [services] - HTML language server state change: starting => running
2020-12-13T11:17:44.918 INFO (pid:17933) [services] - service html started
2020-12-13T11:22:14.210 WARN (pid:17933) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/home/tony/.vim/plugged/coc.nvim/build/index.js:16589:25)
    at ListManager.init (/home/tony/.vim/plugged/coc.nvim/build/index.js:83816:26)
    at Plugin.init (/home/tony/.vim/plugged/coc.nvim/build/index.js:23986:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/tony/.vim/plugged/coc.nvim/build/index.js:11641:13
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by agtonybarletta** [comment]
Here is the log [html.log](https://github.com/neoclide/coc-html/files/5687417/html.log)

With a minimal vimrc do give me the error above but no output is shown with `:CocCommand workspace.showOutput`

**Comment by chemzqm** [comment]
Try update coc.nvim.

**Comment by agtonybarletta** [comment]
The server seems to be running
`:CocInfo`
```
2020-12-14T10:00:28.595 INFO (pid:32655) [plugin] - coc.nvim 0.0.79-464bb069e2 initialized with node: v12.18.1 after 311ms
2020-12-14T10:00:37.012 INFO (pid:32655) [services] - registered service "html"
2020-12-14T10:00:37.013 INFO (pid:32655) [services] - HTML language server state change: stopped => starting
2020-12-14T10:00:37.030 INFO (pid:32655) [language-client-index] - html started with 32691
2020-12-14T10:00:37.438 INFO (pid:32655) [services] - HTML language server state change: starting => running
2020-12-14T10:00:37.453 INFO (pid:32655) [services] - service html started
```

But now `:CocList extensions` doesn't give any *Connection is disposed.* error.
The language server log gives the same output as before

**Comment by agtonybarletta** [comment]
The error *ConnectionError: Connection is disposed.* seems be gone. It doesn't throw that error anymore.
The language server client continue to not working. No diagnostic is given, nor errror highliting.
I tried to use an external server language (vscode-html-language-server)
I installed it outside coc-html and added in coc-settings.json

```
 	"languageserver": {
	  "vscode-html": {
		"command": "~/.local/share/npm/npm-global/bin/vscode-html-language-server",
		"args": ["--stdio"],
		"filetypes": ["html"],
		"cwd": "./src",
		"initializationOptions": {
		},
		"settings": {
			"html.trace.server": "verbose"
		}
	  }
	}
```

But this didn't work either. Seems to be an coc-html error. Other coc linters work great.

**Comment by chemzqm** [comment]
I can't reproduce.
